'use client'
import { useEffect, useState } from 'react'
import useSWR from 'swr'
import { ArrowLeft, Camera, ChevronRight, Clock3, Mail, Mic, Plus, ShieldCheck } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Input } from '@/components/ui/input'
import { Textarea } from '@/components/ui/textarea'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Badge } from '@/components/ui/badge'
import { useHarbor, makeId } from '@/lib/harbor/store'
import { getMedia, saveMedia } from '@/lib/harbor/media'
import type { Dispatch } from '@/lib/harbor/model'
import { ResolutionChoices } from './resolution'
import { toast } from 'sonner'
function LocalMedia({id,kind}:{id:string;kind:string}) {
 const {data,error}=useSWR(['harbor-media',id],()=>getMedia(id));const [url,setUrl]=useState<string>()
 useEffect(()=>{if(!data)return;const url=URL.createObjectURL(data);setUrl(url);return()=>URL.revokeObjectURL(url)},[data])
 if(error)return <p className="small-copy">This attachment could not be opened. Your note is still here.</p>
 if(!url)return <p className="small-copy">Opening your local attachment…</p>
 return kind==='audio'?<audio controls src={url} className="w-full"/>:<img src={url} alt="A little moment captured by Mom in this demo" className="w-full max-h-72 rounded-xl object-cover"/>
}
export function DispatchScreen({navigate}:{navigate:(page:string)=>void}) {
 const {state,update}=useHarbor();const [selected,setSelected]=useState<string|null>(null);const [busy,setBusy]=useState(false)
 if(!state)return null
 const item=state.dispatches.find(d=>d.id===selected)
 const patch=(id:string,values:Partial<Dispatch>)=>update(s=>({...s,dispatches:s.dispatches.map(d=>d.id===id?{...d,...values}:d)}))
 const create=()=>{const draft=state.dispatches.find(d=>d.status==='draft');if(draft){setSelected(draft.id);return}const id=makeId();update(s=>({...s,dispatches:[...s.dispatches,{id,title:'',body:'',topic:'Just a little catch-up. No college talk today.',kind:'headline',status:'draft'}]}));setSelected(id)}
 const upload=async(file:File)=>{if(!item)return;const audio=file.type.startsWith('audio/');const image=file.type.startsWith('image/');if(!audio&&!image){toast.error('Choose an image or audio file.');return}if(file.size>10*1024*1024){toast.error('Please choose a file smaller than 10 MB.');return}setBusy(true);try{const id=makeId();await saveMedia(id,file);patch(item.id,{mediaId:id,kind:audio?'audio':'photo'});toast.success('Attachment saved only on this device.')}catch{toast.error('Your browser could not save this attachment. You can still send a text note.')}finally{setBusy(false)}}
 const queue=()=>{if(!item)return;const isDelayed=item.kind==='audio';patch(item.id,{status:isDelayed?'queued':'delivered',...(isDelayed?{due:new Date(Date.now()+(1+Math.floor(Math.random()*3))*60000).toISOString()}:{})});toast.success(isDelayed?'Tide Mail is tucked away for a little later.':'A little note has arrived in the local demo.');setSelected(null)}
 return <div className="entrance"><div className="page-intro"><div className="eyebrow mb-2">From home, with love</div><h1>The little things.</h1><p>A front page for the ordinary, lovely stuff.</p></div><div className="page-content !pt-0 flow">
 {!item?<><button className="together-card" onClick={create}><span className="flex items-center gap-3"><Plus className="size-5"/><span><strong>Leave a little dispatch</strong><p>Try Mom&apos;s composer · demo preview</p></span></span><ChevronRight className="size-5"/></button>{state.dispatches.slice().reverse().map(d=><button key={d.id} className="surface text-left flow" onClick={()=>setSelected(d.id)}><div className="flex items-center justify-between"><span className="flex items-center gap-2 text-sm text-muted-foreground">{d.kind==='audio'?<Mic className="size-4"/>:d.kind==='photo'?<Camera className="size-4"/>:<Mail className="size-4"/>} From Mom</span><Badge variant="secondary">{d.status==='logged'?'Kept in your garden':d.status==='queued'?'For a little later':d.status==='draft'?'Draft':d.status==='rendered'?'Preview':'A little note'}</Badge></div><h2 className="font-serif text-2xl">{d.title||'An unfinished little thought.'}</h2><p className="small-copy line-clamp-2">{d.body||'Pick up where you left off.'}</p>{d.status==='queued'&&<p className="notice"><Clock3/>Intentionally delayed. Available after {new Date(d.due!).toLocaleTimeString('en',{hour:'numeric',minute:'2-digit'})} when Harbor is open.</p>}</button>)}<p className="notice"><ShieldCheck/>No real delivery. Unanswered notes stay quietly here and remain available in the next edition—never overdue.</p></>:<>
 <button className="text-link self-start" onClick={()=>setSelected(null)}><ArrowLeft/>All little notes</button>
 {item.status==='draft'?<form className="flow" onSubmit={e=>{e.preventDefault();if(!item.title.trim()||!item.body.trim()){toast.error('Add a headline and a little note.');return}patch(item.id,{status:'rendered'})}}><Badge variant="secondary">Mom&apos;s composer · simulated parent view</Badge><FieldGroup><Field><FieldLabel htmlFor="dispatch-title">Today&apos;s headline</FieldLabel><Input id="dispatch-title" required maxLength={100} placeholder="The jasmine is finally blooming." value={item.title} onChange={e=>patch(item.id,{title:e.target.value})}/></Field><Field><FieldLabel htmlFor="dispatch-body">The little story</FieldLabel><Textarea id="dispatch-body" required maxLength={3000} placeholder="Nothing is too ordinary to share…" value={item.body} onChange={e=>patch(item.id,{body:e.target.value})}/></Field><Field><FieldLabel htmlFor="topic">What feels comfortable to talk about?</FieldLabel><Textarea id="topic" required maxLength={300} value={item.topic} onChange={e=>patch(item.id,{topic:e.target.value})}/></Field><Field><FieldLabel htmlFor="attachment">A photo or a voice note (optional)</FieldLabel><Input id="attachment" type="file" accept="image/*,audio/*" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file)}}/></Field></FieldGroup><p className="small-copy">Choose an existing photo or audio recording, up to 10 MB. Audio becomes Tide Mail and arrives intentionally 1–3 minutes later. No microphone is activated.</p>{item.mediaId&&<><LocalMedia id={item.mediaId} kind={item.kind}/><Button variant="ghost" onClick={()=>patch(item.id,{mediaId:undefined,kind:'headline'})}>Remove attachment</Button></>}<Button type="submit" disabled={busy}>{busy?'Saving your attachment…':'Preview this little edition'}</Button><p className="small-copy">Your draft saves as you write.</p></form>:item.status==='queued'?<div className="soft-surface flow"><Clock3 className="size-8" strokeWidth={1}/><h2 className="font-serif text-2xl">Taking the scenic route.</h2><p className="small-copy">Tide Mail is intentionally held for a later moment, rather than asking for an instant reply. This one arrives after {new Date(item.due!).toLocaleTimeString('en',{hour:'numeric',minute:'2-digit'})}.</p><p className="small-copy">Keep Harbor open, or come back later. Delivery is reconciled when you return; no background notification is sent.</p><Button variant="outline" onClick={()=>{patch(item.id,{status:'draft',due:undefined});toast.info('Back in your drafts.')}}>Return to draft</Button></div>:<>
 <article className="dispatch-paper flow"><p className="eyebrow text-center">The home edition</p><div className="dispatch-rule"><span>A little dispatch</span><span>With love, Mom</span></div><h2>{item.title}</h2>{item.mediaId&&<LocalMedia id={item.mediaId} kind={item.kind}/>}<p className="whitespace-pre-wrap text-base leading-relaxed">{item.body}</p><div className="soft-surface"><p className="text-sm font-medium mb-1">A little boundary, lovingly set</p><p className="small-copy">{item.topic}</p></div></article>
 {item.status==='rendered'?<><Button onClick={queue}>{item.kind==='audio'?'Queue Tide Mail for later':'Deliver to my demo inbox'}</Button><Button variant="outline" onClick={()=>patch(item.id,{status:'draft'})}>Keep editing</Button></>:item.status==='logged'?<div className="soft-surface"><p className="font-serif text-xl">A little moment, kept.</p><p className="small-copy">Your response is saved in your garden. No real call or delivery took place.</p><button className="text-link" onClick={()=>navigate('garden')}>Visit your garden <ChevronRight/></button></div>:<><p className="small-copy text-center">No right way to reply. Choose what feels like you.</p><ResolutionChoices key={item.id} source="dispatch" onDone={()=>patch(item.id,{status:'logged'})}/><Button variant="ghost" onClick={()=>setSelected(null)}>Leave it for another moment</Button></>}
 </>}
 </>}
 </div></div>
}
