'use client'
import { useState } from 'react'
import { ArrowRight, CalendarClock, ChevronRight, Flower2, Heart, MessageCircle, Phone, Sprout } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from '@/components/ui/dialog'
import { useHarbor } from '@/lib/harbor/store'
import { localDay, people, type Moment } from '@/lib/harbor/model'
export const momentIcon={called:Phone,reacted:Heart,proposed_later:CalendarClock,message:MessageCircle,dismissed:Sprout}
export const momentLabel={called:'A conversation',reacted:'A little love',proposed_later:'A plan for later',message:'A little note',dismissed:'A moment to yourself'}
const pins=[{left:'25%',top:'37%'},{left:'52%',top:'27%'},{left:'67%',top:'48%'},{left:'39%',top:'59%'},{left:'21%',top:'57%'},{left:'48%',top:'42%'},{left:'60%',top:'67%'},{left:'73%',top:'32%'}]
export function Garden({navigate}:{navigate:(page:string)=>void}) {
 const {state}=useHarbor();const [month,setMonth]=useState(localDay().slice(0,7));const [selected,setSelected]=useState<Moment|null>(null);const [recap,setRecap]=useState(false)
 if(!state)return null
 const moments=state.moments.filter(x=>x.kind!=='dismissed');const filtered=moments.filter(x=>localDay(new Date(x.at)).slice(0,7)===month);const months=Array.from(new Set([localDay().slice(0,7),...moments.map(m=>localDay(new Date(m.at)).slice(0,7))])).sort().reverse();const monthName=new Date(`${month}-01T12:00`).toLocaleDateString('en',{month:'long'});const calls=filtered.filter(m=>m.kind==='called').length
 return <div className="entrance"><div className="page-intro !pb-0"><div className="eyebrow mb-2">The little things add up</div><h1>Look what&apos;s growing.</h1><p>A garden made of moments, not milestones.</p></div>
 <div className="garden-scene"><img src="/images/garden.png" alt="A hand-painted garden of daisies and buttercups, with stepping stones and a little watering can"/>{moments.slice(-8).map((m,i)=><button key={m.id} className="plant-pin" style={pins[i]} aria-label={`Open moment: ${m.text}`} onClick={()=>setSelected(m)}><Flower2 strokeWidth={1.4}/></button>)}</div>
 <div className="page-content !pt-0"><div className="flow"><div className="text-center"><p className="font-serif text-xl">{moments.length} little moments, rooted in love.</p><p className="small-copy">Tap a flower to remember. Nothing here ever wilts.</p></div>
 <section className="soft-surface flex items-center gap-5"><div className="jar" role="img" aria-label={`${state.jarDays.length} ${state.jarDays.length===1?'day':'days'} in your jar of happiness`}><span className="jar-lid" aria-hidden="true"/><span className="jar-body" aria-hidden="true"><span className="jar-fill" style={{height:`${state.jarDays.length===0?6:Math.min(94,18+state.jarDays.length*7)}%`}}>{Array.from({length:Math.min(state.jarDays.length,12)},(_,i)=><Heart key={i}/>)}</span></span><span className="jar-count" aria-hidden="true">{state.jarDays.length}</span></div><div><h2 className="font-serif text-xl">Your jar of happiness</h2><p className="small-copy">{state.settings.minimum?`${state.jarDays.length} ${state.jarDays.length===1?'day':'days'} of your kind of enough. It fills, never drains.`:'You decide what feels like enough. Every little bit counts, on your terms.'}</p><button className="text-link" onClick={()=>navigate('settings')}>{state.settings.minimum?'Your definition of enough':'Choose your kind of enough'}<ChevronRight/></button></div></section>
 <section className="flow"><div className="section-heading"><h2>A month to remember</h2><Flower2 className="size-5 muted-icon"/></div><label className="sr-only" htmlFor="recap-month">Recap month</label><select className="select" id="recap-month" value={month} onChange={e=>setMonth(e.target.value)}>{months.map(m=><option key={m} value={m}>{new Date(`${m}-01T12:00`).toLocaleDateString('en',{month:'long',year:'numeric'})}</option>)}</select><button className="gold-surface text-left flow" onClick={()=>setRecap(true)}><div className="flex justify-between items-start"><span className="eyebrow">Your {monthName} chapter</span><Sunflower/></div><h3 className="font-serif text-3xl leading-tight">Not always in the same place.<br/>Still, growing together.</h3><div className="flex justify-between items-center"><p className="small-copy">{filtered.length} moments worth keeping.</p><span className="icon-button border"><ArrowRight/></span></div></button></section>
 <section><div className="section-heading"><h2>Little things, kept.</h2></div>{filtered.length?filtered.slice().reverse().map(m=>{const Icon=momentIcon[m.kind];return <button key={m.id} className="moment-row w-full text-left" onClick={()=>setSelected(m)}><span className="moment-icon"><Icon/></span><span className="flex-1 min-w-0"><span className="text-sm block font-medium">{m.text}</span><span className="small-copy">{people.find(p=>p.id===m.person)?.name??'Family'} · {new Date(m.at).toLocaleDateString('en',{month:'short',day:'numeric'})}</span></span><ChevronRight className="size-4 shrink-0"/></button>}):<p className="small-copy py-6">A fresh page. Your next connection can be the first little flower.</p>}</section><p className="demo-footnote">Seeded sample moments + your own demo connections</p>
 </div></div>
 <Dialog open={!!selected} onOpenChange={open=>!open&&setSelected(null)}><DialogContent><DialogHeader><DialogTitle>{selected?momentLabel[selected.kind]:''}</DialogTitle><DialogDescription>{selected&&new Date(selected.at).toLocaleDateString('en',{month:'long',day:'numeric',year:'numeric'})}</DialogDescription></DialogHeader><Flower2 className="size-10 text-primary" strokeWidth={1}/><p className="font-serif text-xl">{selected?.text}</p><p className="small-copy">With {people.find(p=>p.id===selected?.person)?.name??'family'}. {selected?.kind==='proposed_later'?'A future plan, not a completed call.':'A little moment that stays.'}</p>{selected?.proposedTime&&<p className="small-copy">Planned for {new Date(selected.proposedTime).toLocaleString()}</p>}<Button variant="outline" onClick={()=>setSelected(null)}>Keep this memory</Button></DialogContent></Dialog>
 <Dialog open={recap} onOpenChange={setRecap}><DialogContent><DialogHeader><DialogTitle>Your {monthName}, together.</DialogTitle><DialogDescription>Some of the best things were the smallest things. All figures come from your demo connection ledger.</DialogDescription></DialogHeader><div className="flex justify-around text-center py-4"><div><p className="recap-number">{calls}</p><p className="small-copy">conversations</p></div><div><p className="recap-number">{filtered.filter(m=>m.kind==='reacted'||m.kind==='message').length}</p><p className="small-copy">little notes & love</p></div><div><p className="recap-number">{filtered.filter(m=>m.kind==='proposed_later').length}</p><p className="small-copy">future plans</p></div></div><p className="font-serif text-xl text-center">{filtered[0]?.text??'A new chapter, ready for you.'}</p><p className="small-copy text-center">No comparison. No catching up. Just your family&apos;s own story.</p><Button onClick={()=>setRecap(false)}>Back to your garden</Button></DialogContent></Dialog>
 </div>
}
function Sunflower(){return <Flower2 className="size-8" strokeWidth={1}/>}
