'use client'
import { useState } from 'react'
import { ChevronRight, Flower2, LockKeyhole, Play, ShieldCheck, SlidersHorizontal, Sprout, Waves } from 'lucide-react'
import { Button } from '@/components/ui/button'
import { Switch } from '@/components/ui/switch'
import { Input } from '@/components/ui/input'
import { Field, FieldGroup, FieldLabel } from '@/components/ui/field'
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog'
import { chime, useHarbor } from '@/lib/harbor/store'
import { clearMedia } from '@/lib/harbor/media'
import { toast } from 'sonner'
export function SettingsScreen({navigate}:{navigate:(page:string)=>void}) {
 const {state,update,reset}=useHarbor();const [privacy,setPrivacy]=useState(false);const [resetOpen,setResetOpen]=useState(false)
 if(!state)return null
 const settings=state.settings
 return <div className="entrance"><div className="page-intro"><div className="eyebrow mb-2">Always on your terms</div><h1>Your kind of Harbor.</h1><p>A little space that fits your life.</p></div><div className="page-content !pt-0 flow">
 <section className="surface flow"><h2 className="font-serif text-xl">Make yourself at home</h2><Field><FieldLabel htmlFor="profile-name">What should we call you?</FieldLabel><Input id="profile-name" maxLength={40} value={state.name} onChange={e=>update(s=>({...s,name:e.target.value}))} onBlur={()=>{if(!state.name.trim())update(s=>({...s,name:'Maya'}))}}/></Field><p className="notice"><LockKeyhole/>No account, no tracking. This sample family lives only in your browser. Please don&apos;t add sensitive information to the demo.</p></section>
 <section className="surface flow"><div className="flex items-center gap-2"><Flower2 className="size-5"/><h2 className="font-serif text-xl">Your definition of enough</h2></div><p className="small-copy">Choose what fills your Jar of Happiness. There are no streaks. Changing your mind never takes away a day you&apos;ve already kept.</p><Field><FieldLabel htmlFor="minimum">A day feels connected when…</FieldLabel><select className="select" id="minimum" value={settings.minimum??''} onChange={e=>update(s=>({...s,settings:{...s.settings,minimum:(e.target.value||null) as 'any'|'call'|null}}))}><option value="">I haven&apos;t decided yet</option><option value="any">I call, send a note, react, or make a plan</option><option value="call">I complete a call, however short</option></select></Field><p className="small-copy">Applies to new moments. Your garden keeps every connection either way.</p></section>
 <section className="surface flow"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><Waves className="size-5"/><h2 className="font-serif text-xl">Slack Tide</h2></div><Switch aria-label="Enable manual demo cues" checked={settings.cuesEnabled} onCheckedChange={enabled=>enabled?setPrivacy(true):update(s=>({...s,settings:{...s.settings,cuesEnabled:false}}))}/></div><p className="small-copy">A gentle cue at the end of a walk. In this web demo, you simulate the moment yourself. No background activity or app usage is sensed.</p>
 <form className="flow" key={`${settings.walkingMinutes}-${settings.dailyCap}-${settings.cooldownMinutes}`} onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);const walkingMinutes=Number(f.get('walking')),sessionMinutes=Number(f.get('session')),dailyCap=Number(f.get('cap')),cooldownMinutes=Number(f.get('cooldown'));if(![walkingMinutes,sessionMinutes,dailyCap,cooldownMinutes].every(Number.isInteger)||walkingMinutes<1||walkingMinutes>120||sessionMinutes<1||sessionMinutes>180||dailyCap<1||dailyCap>10||cooldownMinutes<1||cooldownMinutes>1440){toast.error('Please use values within the shown limits.');return}update(s=>({...s,settings:{...s.settings,walkingMinutes,sessionMinutes,dailyCap,cooldownMinutes}}));toast.success('Your pace, saved.')}}><FieldGroup><div className="grid grid-cols-2 gap-3"><Field><FieldLabel htmlFor="walking">Walking minutes</FieldLabel><Input id="walking" name="walking" type="number" min={1} max={120} required defaultValue={settings.walkingMinutes}/></Field><Field><FieldLabel htmlFor="session">Session minutes</FieldLabel><Input id="session" name="session" type="number" min={1} max={180} required defaultValue={settings.sessionMinutes}/></Field><Field><FieldLabel htmlFor="cap">Daily cue limit</FieldLabel><Input id="cap" name="cap" type="number" min={1} max={10} required defaultValue={settings.dailyCap}/></Field><Field><FieldLabel htmlFor="cooldown">Cooldown minutes</FieldLabel><Input id="cooldown" name="cooldown" type="number" min={1} max={1440} required defaultValue={settings.cooldownMinutes}/></Field></div></FieldGroup><p className="small-copy">Suggested values, always editable. Session sensitivity is saved for future native support; this demo simulates walking only.</p><Button type="submit" variant="outline">Save my pace</Button></form>
 <Field><FieldLabel htmlFor="sound">Your gentle sound</FieldLabel><div className="flex gap-2"><select id="sound" className="select" value={settings.sound} onChange={e=>update(s=>({...s,settings:{...s.settings,sound:e.target.value as typeof settings.sound}}))}><option value="chime">Little chime</option><option value="soft">Soft note</option><option value="silent">Silence</option></select><Button variant="outline" size="icon" aria-label="Preview sound" disabled={settings.sound==='silent'} onClick={()=>chime(settings.sound)}><Play/></Button></div></Field><Button variant="outline" onClick={()=>navigate('tide')}>Try a demo moment <ChevronRight data-icon="inline-end"/></Button></section>
 <section className="surface flow"><div className="flex items-center justify-between"><div><h2 className="font-serif text-xl">A little less movement</h2><p className="small-copy">Reduce interface animations.</p></div><Switch aria-label="Reduce motion" checked={settings.reducedMotion} onCheckedChange={reducedMotion=>update(s=>({...s,settings:{...s.settings,reducedMotion}}))}/></div></section>
 <button className="surface flex items-center justify-between text-left" onClick={()=>navigate('harvest')}><span className="flex items-center gap-3"><ShieldCheck className="size-5"/>Mutual sharing & privacy</span><ChevronRight className="size-4"/></button><Button variant="outline" onClick={()=>setResetOpen(true)}>Start the demo fresh</Button><p className="demo-footnote">Harbor · a little closer, every day.<br/>Local demo. No real calls, messages, or calendar access.</p>
 </div>
 <Dialog open={privacy} onOpenChange={setPrivacy}><DialogContent><DialogHeader><DialogTitle>A cue, never a demand.</DialogTitle><DialogDescription>Slack Tide waits for a quiet moment you explicitly simulate. Activity stays private and is never shared with your family. You can dismiss every cue without a penalty.</DialogDescription></DialogHeader><p className="notice"><ShieldCheck/>This web version does not request motion permissions, monitor other apps, or notify you while the page is closed.</p><Button onClick={()=>{update(s=>({...s,settings:{...s.settings,cuesEnabled:true}}));setPrivacy(false)}}>Enable manual demo cues</Button><Button variant="ghost" onClick={()=>setPrivacy(false)}>Not now</Button></DialogContent></Dialog>
 <Dialog open={resetOpen} onOpenChange={setResetOpen}><DialogContent><DialogHeader><DialogTitle>A fresh patch of ground?</DialogTitle><DialogDescription>This clears your local messages, media, schedules, preferences, and garden moments and restores the sample family. It cannot be undone.</DialogDescription></DialogHeader><Button onClick={async()=>{try{await clearMedia();reset();setResetOpen(false);navigate('home');toast.success('A fresh little Harbor.')}catch{toast.error('Could not clear local media. Please try again.')}}}>Reset all demo data</Button><Button variant="ghost" onClick={()=>setResetOpen(false)}>Keep my garden</Button></DialogContent></Dialog>
 </div>
}
